pipelines:
  gocd-rocketchat-plugin:
    group: gocd
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - build:
          clean_workspace: true
          elastic_profile_id: w.c2.m2048.e10
          artifacts:
           - build:
               source: build/libs/*.jar
               destination: build/libs
          tasks:
           - exec:
               command: ide
               arguments:
                - gradle test jar
